/*
 * tools/fetch-photos.mjs — download and prepare the field photographs.
 *
 *   node tools/fetch-photos.mjs            fetch anything missing
 *   node tools/fetch-photos.mjs --force    re-fetch everything
 *   node tools/fetch-photos.mjs --width=1100 --quality=82
 *
 * Reads src/photo-sources.json, downloads each enabled photo, trims it to a
 * 4:3 landscape crop, resizes and re-encodes it, and writes
 * assets/photos/<pest>-<n>.jpg plus assets/photos/manifest.json.
 *
 * Two rules it will not break:
 *   1. A photo with no recorded photographer is never written into the
 *      manifest. CC BY requires the credit; guessing it is worse than
 *      shipping without the picture.
 *   2. Downloads that fail (blocked host, dead link) are reported and skipped,
 *      never silently dropped. Re-running picks them up.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import sharp from 'sharp';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(REPO, 'src', 'photo-sources.json');
const OUT = path.join(REPO, 'assets', 'photos');

const arg = (k, d) => {
  const hit = process.argv.find(a => a.startsWith('--' + k + '='));
  return hit ? hit.split('=')[1] : (process.argv.includes('--' + k) ? true : d);
};
const WIDTH = parseInt(arg('width', '1000'), 10);
const QUALITY = parseInt(arg('quality', '78'), 10);
const FORCE = !!arg('force', false);

const CACHE = path.join(OUT, '.cache');
fs.mkdirSync(CACHE, { recursive: true });
const spec = JSON.parse(fs.readFileSync(SRC, 'utf8'));

const manifest = [];
const failed = [];
const skipped = [];
const counters = {};

for (const p of spec.photos) {
  if (!p.enabled) { skipped.push({ ...p, why: p.credit ? 'disabled' : 'no photographer recorded' }); continue; }
  if (!p.credit) { skipped.push({ ...p, why: 'no photographer recorded — CC BY needs the credit' }); continue; }

  counters[p.pest] = (counters[p.pest] || 0) + 1;
  const name = `${p.pest}-${counters[p.pest]}.jpg`;
  const file = path.join(OUT, name);

  if (!FORCE && !arg('recrop', false) && fs.existsSync(file)) {
    manifest.push(entry(p, name, file));
    console.log('have   ', name);
    continue;
  }

  try {
    // keep the untouched download so crops can be re-cut without re-fetching
    const raw = path.join(CACHE, `${p.pest}-${counters[p.pest]}.raw`);
    if (FORCE || !fs.existsSync(raw)) {
      const res = await fetch(p.url, {
        headers: { 'User-Agent': 'Bugboss pest-dossier build (Slug-A-Bug Pest Control)' }
      });
      if (!res.ok) throw new Error('HTTP ' + res.status);
      fs.writeFileSync(raw, Buffer.from(await res.arrayBuffer()));
    }

    let img = sharp(fs.readFileSync(raw)).rotate();
    // `crop` is [left, top, width, height] in 0–1 of the source frame. Wildlife
    // snaps often put the subject in a corner, and an automatic salience crop
    // will happily frame the leaf instead of the ant.
    if (p.crop) {
      const m = await img.metadata();
      const [l, t, w, h] = p.crop;
      img = img.extract({
        left: Math.round(l * m.width),
        top: Math.round(t * m.height),
        width: Math.max(8, Math.round(w * m.width)),
        height: Math.max(8, Math.round(h * m.height))
      });
    }
    await img
      .resize(WIDTH, Math.round(WIDTH * 3 / 4), {
        fit: 'cover',
        position: p.crop ? 'centre' : sharp.strategy.attention
      })
      .jpeg({ quality: QUALITY, mozjpeg: true })
      .toFile(file);

    manifest.push(entry(p, name, file));
    console.log('fetched', name, (fs.statSync(file).size / 1024).toFixed(0) + ' KB');
  } catch (e) {
    failed.push({ pest: p.pest, url: p.url, error: e.message });
    console.error('FAILED ', p.pest, '—', e.message);
  }
}

function entry(p, name, file) {
  const meta = { pest: p.pest, file: name, credit: p.credit, licence: p.licence, source: p.source, url: p.url };
  try {
    const s = fs.statSync(file);
    meta.bytes = s.size;
  } catch { /* not written yet */ }
  return meta;
}

fs.writeFileSync(path.join(OUT, 'manifest.json'), JSON.stringify(manifest, null, 2));

/* Generated index the app reads. Metadata only — the image bytes stay in
 * assets/photos/ for the dev pages, and build.js inlines them as data URIs
 * for the single-file distribution. */
const byPest = {};
for (const m of manifest) (byPest[m.pest] = byPest[m.pest] || []).push({
  file: m.file, credit: m.credit, licence: m.licence, source: m.source
});
fs.writeFileSync(path.join(REPO, 'src', 'photos.js'),
  `/*\n * photos.js — GENERATED by tools/fetch-photos.mjs. Do not hand-edit.\n` +
  ` * Edit src/photo-sources.json and re-run the fetcher instead.\n` +
  ` *\n * Every entry carries its photographer and licence because the pictures are\n` +
  ` * Creative Commons: the credit has to stay visible wherever they appear.\n */\n` +
  `(function (root) {\n  'use strict';\n  var BB = (root.BB = root.BB || {});\n` +
  `  BB.PHOTO_BASE = 'assets/photos/';\n` +
  `  BB.PHOTOS = ${JSON.stringify(byPest, null, 2).replace(/\n/g, '\n  ')};\n` +
  `  /** Data URI when the build inlined it, relative path otherwise. */\n` +
  `  BB.photoSrc = function (file) {\n` +
  `    return (BB.PHOTO_DATA && BB.PHOTO_DATA[file]) || BB.PHOTO_BASE + file;\n` +
  `  };\n` +
  `})(typeof window !== 'undefined' ? window : globalThis);\n`);

console.log(`\n${manifest.length} photo(s) ready in assets/photos/`);
if (skipped.length) {
  console.log(`\n${skipped.length} skipped:`);
  for (const s of skipped) console.log('  ' + s.pest.padEnd(24) + s.why);
}
if (failed.length) {
  console.log(`\n${failed.length} failed to download:`);
  for (const f of failed) console.log('  ' + f.pest.padEnd(24) + f.error + '  ' + f.url);
  console.log('\nRe-run this from a machine that can reach those hosts, or drop the');
  console.log('files into assets/photos/ named <pest>-1.jpg and add them to the manifest.');
}
