/*
 * photos.js — GENERATED by tools/fetch-photos.mjs. Do not hand-edit.
 * Edit src/photo-sources.json and re-run the fetcher instead.
 *
 * Every entry carries its photographer and licence because the pictures are
 * Creative Commons: the credit has to stay visible wherever they appear.
 */
(function (root) {
  'use strict';
  var BB = (root.BB = root.BB || {});
  BB.PHOTO_BASE = 'assets/photos/';
  BB.PHOTOS = {
    "german-cockroach": [
      {
        "file": "german-cockroach-1.jpg",
        "credit": "Terra Occ",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "american-cockroach": [
      {
        "file": "american-cockroach-1.jpg",
        "credit": "smathichong",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "coastal-brown-ant": [
      {
        "file": "coastal-brown-ant-1.jpg",
        "credit": "Zoe Anthony Quested",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "black-house-ant": [
      {
        "file": "black-house-ant-1.jpg",
        "credit": "Carl Ramirez",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "subterranean-termite": [
      {
        "file": "subterranean-termite-1.jpg",
        "credit": "Scott W. Gavins",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "redback-spider": [
      {
        "file": "redback-spider-1.jpg",
        "credit": "Lawrence Hylton",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "huntsman-spider": [
      {
        "file": "huntsman-spider-1.jpg",
        "credit": "Noah Kirkland",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "white-tailed-spider": [
      {
        "file": "white-tailed-spider-1.jpg",
        "credit": "koalabi",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "roof-rat": [
      {
        "file": "roof-rat-1.jpg",
        "credit": "Austen Armstrong",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "house-mouse": [
      {
        "file": "house-mouse-1.jpg",
        "credit": "Tyler Anthony",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "bed-bug": [
      {
        "file": "bed-bug-1.jpg",
        "credit": "Sarah Courchesne",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "paper-wasp": [
      {
        "file": "paper-wasp-1.jpg",
        "credit": "Mark Clarke",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "european-wasp": [
      {
        "file": "european-wasp-1.jpg",
        "credit": "Lukas Clews",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ],
    "pantry-moth": [
      {
        "file": "pantry-moth-1.jpg",
        "credit": "smathichong",
        "licence": "CC BY 4.0",
        "source": "iNaturalist"
      }
    ]
  };
  /** Data URI when the build inlined it, relative path otherwise. */
  BB.photoSrc = function (file) {
    return (BB.PHOTO_DATA && BB.PHOTO_DATA[file]) || BB.PHOTO_BASE + file;
  };
})(typeof window !== 'undefined' ? window : globalThis);
