"""Authored per-sector content for the Slug-A-Bug Partner Packs.

One PROFILES entry per sector. Every entry carries only the *authored* fields;
`engine.py` expands them into the ~120 copy slots the seven page layouts need.

Field guide
-----------
identity   industry, tag, so_word, focus, job_prefix, prevention_title
phrasing   sector, cta_sector, audience, site_word, site_label, risk_clause,
           discreet, so_body
lists      areas11 (Service Overview), areas9 (Quote scope), scope6, access6
story      challenges (3), solutions (4), results (3), why_matters (2), quote,
           attribution
guide      tips (6), urgent (6)
capability core (6), why (5)
report     sr_property, sr_service_type, sr_contact, sr_areas (5),
           sr_findings (4), sr_actions (4), sr_recs (4)

Cover-page copy (tag, subhead, body, four tiles, footer strap) is NOT authored
here — it is read from data/SlugABug_BulkCreate_AllSectors_v4.csv and joined on
`industry`.
"""

PROFILES = {
    # ------------------------------------------------------------------ #
    "schools": {
        "industry": "Schools & Education",
        "so_word": "SCHOOLS",
        "prevention_title": "SCHOOLS",
        "focus": "SCHOOLS AND CAMPUSES",
        "job_prefix": "SC",
        "sector": "schools, colleges and education facilities",
        "cta_sector": "school",
        "audience": "School business managers and facilities teams",
        "site_word": "school",
        "site_label": "School name:",
        "risk_clause": "keep students, staff and visitors safe",
        "discreet": "We work quietly around class times and school routines.",
        "so_body": "Slug-A-Bug helps schools, colleges and education facilities "
                   "reduce pest pressure across busy campuses, keep records clear "
                   "and respond quickly when issues are reported.",
        "areas11": ["Classrooms", "Staff rooms", "Tuckshops and canteens",
                    "Kitchens", "Amenities", "Storage rooms", "Libraries",
                    "Bin areas", "Sports and hall buildings", "Grounds and gardens",
                    "Perimeters"],
        "areas9": ["Classrooms", "Kitchens and canteens", "Staff rooms",
                   "Amenities", "Libraries", "Storage rooms", "Bin areas",
                   "Grounds and play areas", "Perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Termite inspection", "Targeted treatments",
                   "Wasp nest control", "Preventative school program"],
        "access6": ["Out-of-hours or school-holiday access",
                    "Preferred service times", "Child-safe / safety requirements",
                    "Restricted or secure areas", "Recent pest reports or photos",
                    "Previous service history"],
        "challenges": ["Recurring pest concerns near canteen and waste areas.",
                       "Staff reported occasional ant and cockroach activity.",
                       "Management wanted clearer reporting across multiple buildings."],
        "solutions": ["Completed a detailed site review.",
                      "Identified risk areas and entry points.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided clear reports and practical recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence from staff and management.",
                    "Better record-keeping and easier internal follow-up."],
        "why_matters": ["School decision-makers need a pest partner who understands "
                        "the importance of safety, compliance and reputation.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Business Manager",
        "tips": ["Keep canteen and food areas clean.",
                 "Report pest sightings with the location and time.",
                 "Reduce clutter in storage and prep rooms.",
                 "Keep doors closed where practical and monitor damaged seals.",
                 "Manage bins and waste areas carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "canteens or storage."),
                   ("Heavy ant or", "cockroach activity."),
                   ("Wasp nests", "near play or sports areas."),
                   ("Fly activity", "around waste areas."),
                   ("Any recurring pest issue", "affecting safety or presentation.")],
        "core": ["Routine pest management for education environments",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Fly management around waste and food areas",
                 "Termite inspections and treatments",
                 "Preventative pest management for grounds and play areas"],
        "why": ["Safe, considered approach", "Minimal disruption",
                "Clear, easy-to-file reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample State Primary School",
        "sr_service_type": "Routine school facility pest service",
        "sr_contact": "Business Manager",
        "sr_areas": ["classrooms", "canteen", "staff room", "bin area", "storage room"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in storage area",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near rear waste area"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided management recommendations"],
        "sr_recs": ["improve waste area sanitation", "seal minor entry gaps",
                    "continue monitoring external play edges",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "childcare": {
        "industry": "Child Care",
        "so_word": "CHILD CARE",
        "prevention_title": "CHILD CARE",
        "focus": "CHILD CARE FACILITIES",
        "job_prefix": "CC",
        "sector": "child care centres, kindergartens and early learning services",
        "cta_sector": "child care",
        "audience": "Child care decision-makers",
        "site_word": "centre",
        "site_label": "Centre name:",
        "risk_clause": "keep children, staff and families safe",
        "discreet": "We work quietly and professionally around children and staff.",
        "so_body": "Slug-A-Bug helps child care centres, early learning services "
                   "and kindergartens reduce pest pressure in sensitive "
                   "environments, keep records clear and respond quickly when "
                   "issues are reported.",
        "areas11": ["Reception areas", "Classrooms", "Sleep rooms", "Kitchens",
                    "Nappy change areas", "Staff rooms", "Storage rooms",
                    "Amenities", "Bin areas", "External play areas", "Perimeters"],
        "areas9": ["Classrooms", "Kitchens", "Sleep rooms", "Nappy change areas",
                   "Staff room", "Storage rooms", "Bin area", "External play areas",
                   "Perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Termite inspection", "Targeted treatments",
                   "Wasp nest control", "Preventative child care program"],
        "access6": ["After-hours access available", "Preferred service times",
                    "Child-safe / safety requirements", "Restricted areas",
                    "Recent pest reports or photos", "Previous service history"],
        "challenges": ["Recurring pest concerns near play and waste areas.",
                       "Staff reported occasional ant and cockroach activity.",
                       "Management wanted clearer reporting and confidence in the program."],
        "solutions": ["Completed a detailed site review.",
                      "Identified risk areas and entry points.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided clear reports and practical recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence from management and staff.",
                    "Better record-keeping and easier internal follow-up."],
        "why_matters": ["Child care decision-makers need a pest partner who "
                        "understands the importance of safety, compliance and "
                        "reputation.",
                        "They want responsive service, clear paperwork and "
                        "practical results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Centre Director",
        "tips": ["Keep food and snack areas clean.",
                 "Report pest sightings with the location and time.",
                 "Reduce clutter in storage rooms.",
                 "Keep doors closed where practical and monitor damaged seals.",
                 "Manage bins and waste areas carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "kitchens or storage."),
                   ("Heavy ant or", "cockroach activity."),
                   ("Wasp nests", "near play areas."),
                   ("Fly activity", "around waste areas."),
                   ("Any recurring pest issue", "affecting safety or presentation.")],
        "core": ["Routine pest management for child care environments",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Fly management around waste and food areas",
                 "Termite inspections and treatments",
                 "Preventative pest management for internal and external play areas"],
        "why": ["Child-safe approach", "Minimal disruption",
                "Clear, easy-to-file reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Early Learning Centre",
        "sr_service_type": "Routine child care facility pest service",
        "sr_contact": "Centre Director",
        "sr_areas": ["reception area", "kitchen", "outdoor play area", "bin area",
                     "storage room"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in storage area",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near rear waste area"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided management recommendations"],
        "sr_recs": ["improve waste area sanitation", "seal minor entry gaps",
                    "continue monitoring external play edges",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "universities": {
        "industry": "Universities & TAFE",
        "so_word": "CAMPUS",
        "prevention_title": "CAMPUS",
        "focus": "UNIVERSITY CAMPUSES",
        "job_prefix": "UN",
        "sector": "universities, TAFE campuses and training colleges",
        "cta_sector": "campus",
        "audience": "Campus facilities and property managers",
        "site_word": "campus",
        "site_label": "Campus name:",
        "risk_clause": "keep students, staff and campus buildings protected",
        "discreet": "We work around teaching timetables and campus operations.",
        "so_body": "Slug-A-Bug helps universities, TAFE campuses and training "
                   "colleges manage pest pressure across multiple buildings, keep "
                   "records clear and respond quickly when issues are reported.",
        "areas11": ["Lecture theatres", "Teaching labs", "Libraries", "Staff offices",
                    "Cafes and food outlets", "Commercial kitchens", "Amenities",
                    "Storage and plant rooms", "Bin and waste compounds",
                    "Student accommodation", "Grounds and perimeters"],
        "areas9": ["Lecture theatres", "Teaching labs", "Libraries",
                   "Food outlets and kitchens", "Staff offices", "Amenities",
                   "Storage and plant rooms", "Waste compounds", "Grounds and perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Termite inspection", "Targeted treatments",
                   "Wasp nest control", "Multi-building campus program"],
        "access6": ["Out-of-hours or semester-break access",
                    "Preferred service times", "Site induction requirements",
                    "Restricted or secure areas", "Recent pest reports or photos",
                    "Previous service history"],
        "challenges": ["Recurring pest reports across several campus buildings.",
                       "Food outlets and waste compounds needed closer attention.",
                       "Facilities wanted one clear reporting trail for the whole site."],
        "solutions": ["Completed a detailed multi-building site review.",
                      "Identified risk areas and entry points by building.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided consolidated reports and practical recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence from facilities and faculty staff.",
                    "One consistent record across every building."],
        "why_matters": ["Campus decision-makers need a pest partner who can cover "
                        "many buildings without losing the detail on any of them.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Facilities Manager",
        "tips": ["Keep food outlet and kitchen areas clean.",
                 "Report pest sightings with the building and room number.",
                 "Reduce clutter in storage and plant rooms.",
                 "Keep external doors closed and monitor damaged seals.",
                 "Manage waste compounds carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "food outlets or storage."),
                   ("Heavy ant or", "cockroach activity."),
                   ("Wasp nests", "near walkways or entries."),
                   ("Fly activity", "around waste compounds."),
                   ("Any recurring pest issue", "affecting safety or presentation.")],
        "core": ["Routine pest management for campus environments",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Fly management around waste and food areas",
                 "Termite inspections and treatments",
                 "Multi-building programs with consolidated reporting"],
        "why": ["Multi-building coverage", "Minimal disruption",
                "Clear, easy-to-file reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Campus – Building C",
        "sr_service_type": "Routine campus pest service",
        "sr_contact": "Facilities Manager",
        "sr_areas": ["lecture theatre", "cafeteria", "teaching lab",
                     "waste compound", "plant room"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in plant room",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near waste compound"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided facilities recommendations"],
        "sr_recs": ["improve waste compound sanitation", "seal minor entry gaps",
                    "continue monitoring building perimeters",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "strata": {
        "industry": "Strata & Body Corporate",
        "so_word": "STRATA",
        "prevention_title": "STRATA",
        "focus": "STRATA COMMON PROPERTY",
        "job_prefix": "ST",
        "sector": "body corporate managers, committees and strata schemes",
        "cta_sector": "common property",
        "audience": "Body corporate managers and committees",
        "site_word": "scheme",
        "site_label": "Scheme name:",
        "risk_clause": "protect common property and keep residents comfortable",
        "discreet": "We work respectfully around residents and shared spaces.",
        "so_body": "Slug-A-Bug helps body corporate managers and committees "
                   "manage pest pressure across common property, keep records "
                   "clear for the committee and respond quickly when residents "
                   "report an issue.",
        "areas11": ["Foyers and lobbies", "Common corridors", "Lift lobbies",
                    "Basement car parks", "Bin rooms and chutes", "Plant rooms",
                    "Gyms and common rooms", "Pool surrounds", "Roof and awnings",
                    "Landscaped grounds", "Perimeters"],
        "areas9": ["Foyers and lobbies", "Common corridors", "Basement car park",
                   "Bin rooms and chutes", "Plant rooms", "Common facilities",
                   "Pool surrounds", "Landscaped grounds", "Perimeter"],
        "scope6": ["Routine common property service", "Rodent monitoring program",
                   "Termite inspection", "Targeted treatments",
                   "Wasp nest control", "Bin room and chute program"],
        "access6": ["Key, fob or code access", "Preferred service times",
                    "Resident notification requirements",
                    "Restricted or secure areas", "Recent pest reports or photos",
                    "Previous service history"],
        "challenges": ["Recurring pest reports from residents in shared areas.",
                       "Bin rooms and basement levels needed closer attention.",
                       "The committee wanted a clear scope between common property and lots."],
        "solutions": ["Completed a detailed common property review.",
                      "Identified risk areas and entry points.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided committee-ready reports and clear scope boundaries."],
        "results": ["Noticeable reduction in pest activity.",
                    "Fewer resident complaints reaching the committee.",
                    "Documentation the manager can file and forward."],
        "why_matters": ["Body corporate decision-makers need a pest partner who "
                        "understands common property, budgets and resident "
                        "expectations.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can put in front of a committee."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Body Corporate Manager",
        "tips": ["Keep bin rooms and chutes clean and closed.",
                 "Report pest sightings with the building and level.",
                 "Reduce clutter in basements and store rooms.",
                 "Keep common doors closed and monitor damaged seals.",
                 "Manage shared waste areas carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "bin rooms or basements."),
                   ("Heavy ant or", "cockroach activity."),
                   ("Wasp nests", "near entries or balconies."),
                   ("Fly activity", "around waste areas."),
                   ("Any recurring pest issue", "affecting residents or presentation.")],
        "core": ["Routine pest management for common property",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Fly management around bin rooms and chutes",
                 "Termite inspections and treatments",
                 "Committee-ready reporting and clear scope boundaries"],
        "why": ["Clear common property scope", "Minimal disruption to residents",
                "Committee-ready reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Residential Scheme",
        "sr_service_type": "Routine common property pest service",
        "sr_contact": "Body Corporate Manager",
        "sr_areas": ["foyer", "bin room", "basement car park", "plant room",
                     "landscaped grounds"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in basement car park",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified in bin room"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided committee recommendations"],
        "sr_recs": ["improve bin room sanitation", "seal minor entry gaps",
                    "continue monitoring basement levels",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "residential": {
        "industry": "Residential Communities",
        "so_word": "COMMUNITY",
        "prevention_title": "COMMUNITY",
        "focus": "RESIDENTIAL COMMUNITIES",
        "job_prefix": "RC",
        "sector": "residential communities, lifestyle villages and estates",
        "cta_sector": "community",
        "audience": "Community and village managers",
        "site_word": "community",
        "site_label": "Community name:",
        "risk_clause": "protect homes, shared facilities and residents",
        "discreet": "We work respectfully around residents and their homes.",
        "so_body": "Slug-A-Bug helps residential communities and lifestyle "
                   "villages manage pest pressure across homes and shared "
                   "facilities, keep records clear and respond quickly when "
                   "residents report an issue.",
        "areas11": ["Community centres", "Reception and admin", "Common rooms",
                    "Shared kitchens", "Amenities", "Storage and plant rooms",
                    "Bin and waste areas", "Pool and BBQ areas", "Workshops and sheds",
                    "Gardens and grounds", "Perimeters"],
        "areas9": ["Community centre", "Common rooms", "Shared kitchens",
                   "Amenities", "Storage and plant rooms", "Bin and waste areas",
                   "Pool and BBQ areas", "Gardens and grounds", "Perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Termite inspection", "Targeted treatments",
                   "Wasp nest control", "Whole-of-community program"],
        "access6": ["Gate or key access", "Preferred service times",
                    "Resident notification requirements", "Restricted areas",
                    "Recent pest reports or photos", "Previous service history"],
        "challenges": ["Recurring pest reports from residents across the community.",
                       "Shared facilities and waste areas needed closer attention.",
                       "Management wanted one program covering the whole site."],
        "solutions": ["Completed a detailed whole-of-community review.",
                      "Identified risk areas and entry points.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided clear reports and practical recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence from residents and management.",
                    "Better record-keeping and easier internal follow-up."],
        "why_matters": ["Community decision-makers need a pest partner who "
                        "understands shared facilities, budgets and resident "
                        "expectations.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Community Manager",
        "tips": ["Keep shared kitchens and BBQ areas clean.",
                 "Report pest sightings with the location and time.",
                 "Reduce clutter in sheds and storage areas.",
                 "Keep doors closed where practical and monitor damaged seals.",
                 "Manage bins and waste areas carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "kitchens or storage."),
                   ("Heavy ant or", "cockroach activity."),
                   ("Wasp nests", "near walkways or entries."),
                   ("Fly activity", "around waste areas."),
                   ("Any recurring pest issue", "affecting residents or presentation.")],
        "core": ["Routine pest management for residential communities",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Fly management around waste and BBQ areas",
                 "Termite inspections and treatments",
                 "Whole-of-community programs with clear reporting"],
        "why": ["Respectful of residents", "Minimal disruption",
                "Clear, easy-to-file reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Lifestyle Village",
        "sr_service_type": "Routine community pest service",
        "sr_contact": "Community Manager",
        "sr_areas": ["community centre", "shared kitchen", "bin area",
                     "storage shed", "gardens and grounds"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in storage shed",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near rear waste area"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided management recommendations"],
        "sr_recs": ["improve waste area sanitation", "seal minor entry gaps",
                    "continue monitoring shared facility edges",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "retail": {
        "industry": "Shopping Centres & Retail",
        "so_word": "CENTRE",
        "prevention_title": "SHOPPING CENTRE",
        "focus": "SHOPPING CENTRES",
        "job_prefix": "SH",
        "sector": "shopping centres, retail precincts and centre management teams",
        "cta_sector": "centre",
        "audience": "Centre managers and retail landlords",
        "site_word": "centre",
        "site_label": "Centre name:",
        "risk_clause": "protect tenants, shoppers and centre presentation",
        "discreet": "We service outside trading hours and coordinate with tenants.",
        "so_body": "Slug-A-Bug helps shopping centres and retail precincts manage "
                   "pest pressure across common areas and tenancies, coordinate "
                   "with tenants and respond quickly when issues are reported.",
        "areas11": ["Malls and common areas", "Food courts", "Tenancy kitchens",
                    "Loading docks", "Bin and waste compounds", "Back-of-house corridors",
                    "Amenities", "Plant and service rooms", "Car parks",
                    "Landscaped surrounds", "Perimeters"],
        "areas9": ["Malls and common areas", "Food court", "Tenancy kitchens",
                   "Loading dock", "Waste compound", "Back-of-house corridors",
                   "Amenities", "Car park", "Perimeter"],
        "scope6": ["Routine centre-wide service", "Rodent monitoring program",
                   "Termite inspection", "Targeted treatments",
                   "Wasp nest control", "Tenant coordination program"],
        "access6": ["After-hours or pre-trade access", "Preferred service times",
                    "Contractor induction requirements", "Restricted or secure areas",
                    "Recent pest reports or photos", "Previous service history"],
        "challenges": ["Recurring pest reports from food court tenancies.",
                       "Loading dock and waste compound needed closer attention.",
                       "Centre management wanted one reporting trail across tenancies."],
        "solutions": ["Completed a detailed centre-wide review.",
                      "Identified risk areas and entry points by tenancy.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided consolidated reports and tenant recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence from tenants and centre management.",
                    "One consistent record across the centre."],
        "why_matters": ["Centre decision-makers need a pest partner who can work "
                        "across many tenancies without disrupting trade.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Centre Manager",
        "tips": ["Keep food court and tenancy kitchens clean.",
                 "Report pest sightings with the tenancy and time.",
                 "Reduce clutter in back-of-house corridors.",
                 "Keep dock doors closed and monitor damaged seals.",
                 "Manage waste compounds carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "food courts or docks."),
                   ("Heavy ant or", "cockroach activity."),
                   ("Wasp nests", "near entries or car parks."),
                   ("Fly activity", "around waste compounds."),
                   ("Any recurring pest issue", "affecting tenants or presentation.")],
        "core": ["Routine pest management for retail environments",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Fly management around food courts and waste compounds",
                 "Termite inspections and treatments",
                 "Centre-wide programs with tenant coordination"],
        "why": ["Works outside trading hours", "Minimal disruption to trade",
                "Clear, easy-to-file reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Shopping Centre",
        "sr_service_type": "Routine centre-wide pest service",
        "sr_contact": "Centre Manager",
        "sr_areas": ["food court", "loading dock", "waste compound",
                     "back-of-house corridor", "amenities"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in back-of-house corridor",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified at waste compound"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided tenant and management recommendations"],
        "sr_recs": ["improve waste compound sanitation", "seal minor entry gaps",
                    "continue monitoring dock and tenancy edges",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "industrial": {
        "industry": "Factories & Offices",
        "so_word": "FACILITY",
        "prevention_title": "WORKPLACE",
        "focus": "FACTORIES AND OFFICES",
        "job_prefix": "FO",
        "sector": "factories, warehouses and office environments",
        "cta_sector": "site",
        "audience": "Operations and facilities managers",
        "site_word": "site",
        "site_label": "Site name:",
        "risk_clause": "protect stock, plant and staff areas",
        "discreet": "We work around production runs, shifts and staff areas.",
        "so_body": "Slug-A-Bug helps factories, warehouses and offices manage "
                   "pest pressure across production, storage and staff areas, "
                   "keep records clear and respond quickly when issues are reported.",
        "areas11": ["Reception and offices", "Meeting rooms", "Staff kitchens",
                    "Amenities", "Production areas", "Warehouse and racking",
                    "Loading docks", "Bin and waste areas", "Plant and switch rooms",
                    "External hardstand", "Perimeters"],
        "areas9": ["Offices", "Staff kitchens", "Amenities", "Production areas",
                   "Warehouse and racking", "Loading dock", "Bin and waste areas",
                   "Plant rooms", "Perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Termite inspection", "Targeted treatments",
                   "Wasp nest control", "Warehouse and dock program"],
        "access6": ["Out-of-hours or shift access", "Preferred service times",
                    "Site induction and PPE requirements", "Restricted or plant areas",
                    "Recent pest reports or photos", "Previous service history"],
        "challenges": ["Recurring rodent evidence around dock and racking areas.",
                       "Staff reported occasional ant and cockroach activity.",
                       "Management wanted clearer reporting for audits."],
        "solutions": ["Completed a detailed site review.",
                      "Identified risk areas and entry points.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided audit-ready reports and practical recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence from management and staff.",
                    "Documentation ready for audits and reviews."],
        "why_matters": ["Operations decision-makers need a pest partner who "
                        "understands stock protection, safety and audit "
                        "requirements.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Operations Manager",
        "tips": ["Keep staff kitchens and break areas clean.",
                 "Report pest sightings with the area and time.",
                 "Reduce clutter around racking and storage.",
                 "Keep dock doors closed and monitor damaged seals.",
                 "Manage bins and waste areas carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "docks, racking or storage."),
                   ("Heavy ant or", "cockroach activity."),
                   ("Wasp nests", "near entries or hardstand."),
                   ("Fly activity", "around waste areas."),
                   ("Any recurring pest issue", "affecting stock or staff areas.")],
        "core": ["Routine pest management for industrial and office sites",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Fly management around waste and staff areas",
                 "Termite inspections and treatments",
                 "Audit-ready reporting for warehouses and docks"],
        "why": ["Audit-ready documentation", "Minimal disruption to production",
                "Clear, easy-to-file reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Distribution Facility",
        "sr_service_type": "Routine industrial site pest service",
        "sr_contact": "Operations Manager",
        "sr_areas": ["office area", "staff kitchen", "warehouse racking",
                     "loading dock", "bin area"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in warehouse racking",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near rear waste area"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided management recommendations"],
        "sr_recs": ["improve waste area sanitation", "seal minor entry gaps",
                    "continue monitoring dock and racking edges",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "medical": {
        "industry": "Medical Centres",
        "so_word": "MEDICAL",
        "prevention_title": "MEDICAL CENTRE",
        "focus": "MEDICAL CENTRES",
        "job_prefix": "MC",
        "sector": "medical centres, general practices and healthcare providers",
        "cta_sector": "medical centre",
        "audience": "Practice managers and healthcare decision-makers",
        "site_word": "practice",
        "site_label": "Practice name:",
        "risk_clause": "protect patients, staff and clinical areas",
        "discreet": "We service outside consulting hours and work discreetly.",
        "so_body": "Slug-A-Bug helps medical centres and healthcare practices "
                   "manage pest pressure in clinical environments, keep "
                   "accreditation-ready records and respond quickly when issues "
                   "are reported.",
        "areas11": ["Reception and waiting", "Consulting rooms",
                    "Treatment rooms", "Nurses stations", "Staff rooms",
                    "Amenities", "Clean and dirty utility", "Storage rooms",
                    "Clinical waste areas", "Plant rooms", "Perimeters"],
        "areas9": ["Reception and waiting", "Consulting rooms", "Treatment rooms",
                   "Staff room", "Amenities", "Utility rooms", "Storage rooms",
                   "Bin and waste areas", "Perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Termite inspection", "Targeted treatments",
                   "Wasp nest control", "Accreditation support program"],
        "access6": ["After-hours access available", "Preferred service times",
                    "Infection control requirements", "Restricted clinical areas",
                    "Recent pest reports or photos", "Previous service history"],
        "challenges": ["Recurring pest concerns near waiting and waste areas.",
                       "Staff reported occasional ant and cockroach activity.",
                       "The practice needed documentation ready for accreditation."],
        "solutions": ["Completed a detailed practice review.",
                      "Identified risk areas and entry points.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided accreditation-ready reports and recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence from the practice team.",
                    "Documentation ready for accreditation and audits."],
        "why_matters": ["Practice decision-makers need a pest partner who "
                        "understands clinical environments, infection control and "
                        "accreditation.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Practice Manager",
        "tips": ["Keep staff room and kitchen areas clean.",
                 "Report pest sightings with the room and time.",
                 "Reduce clutter in storage and utility rooms.",
                 "Keep external doors closed and monitor damaged seals.",
                 "Manage clinical and general waste carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "staff rooms or storage."),
                   ("Heavy ant or", "cockroach activity."),
                   ("Wasp nests", "near entries or car parks."),
                   ("Fly activity", "around waste areas."),
                   ("Any recurring pest issue", "affecting patients or presentation.")],
        "core": ["Routine pest management for clinical environments",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Fly management around waste and staff areas",
                 "Termite inspections and treatments",
                 "Accreditation-ready reporting and documentation"],
        "why": ["Clinically aware approach", "Minimal disruption to consulting",
                "Accreditation-ready reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Medical Centre",
        "sr_service_type": "Routine medical centre pest service",
        "sr_contact": "Practice Manager",
        "sr_areas": ["reception and waiting", "consulting rooms", "staff room",
                     "utility room", "bin area"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in storage area",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near rear waste area"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided practice recommendations"],
        "sr_recs": ["improve waste area sanitation", "seal minor entry gaps",
                    "continue monitoring external entry points",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "dental": {
        "industry": "Dental Practices",
        "so_word": "DENTAL",
        "prevention_title": "DENTAL PRACTICE",
        "focus": "DENTAL PRACTICES",
        "job_prefix": "DP",
        "sector": "dental practices and specialist clinics",
        "cta_sector": "dental practice",
        "audience": "Practice managers and principal dentists",
        "site_word": "practice",
        "site_label": "Practice name:",
        "risk_clause": "protect patients, staff and surgery areas",
        "discreet": "We service outside appointment hours and work discreetly.",
        "so_body": "Slug-A-Bug helps dental practices and specialist clinics "
                   "manage pest pressure in clinical environments, keep "
                   "compliance-ready records and respond quickly when issues are "
                   "reported.",
        "areas11": ["Reception and waiting", "Surgeries", "Sterilisation room",
                    "Lab areas", "Staff rooms", "Amenities", "Storage rooms",
                    "Compressor and plant rooms", "Clinical waste areas",
                    "External surrounds", "Perimeters"],
        "areas9": ["Reception and waiting", "Surgeries", "Sterilisation room",
                   "Lab area", "Staff room", "Amenities", "Storage rooms",
                   "Bin and waste areas", "Perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Termite inspection", "Targeted treatments",
                   "Wasp nest control", "Compliance support program"],
        "access6": ["After-hours access available", "Preferred service times",
                    "Infection control requirements", "Restricted clinical areas",
                    "Recent pest reports or photos", "Previous service history"],
        "challenges": ["Recurring pest concerns near waiting and waste areas.",
                       "Staff reported occasional ant and cockroach activity.",
                       "The practice needed documentation ready for compliance reviews."],
        "solutions": ["Completed a detailed practice review.",
                      "Identified risk areas and entry points.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided compliance-ready reports and recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence from the practice team.",
                    "Documentation ready for compliance reviews."],
        "why_matters": ["Dental decision-makers need a pest partner who "
                        "understands clinical environments, infection control and "
                        "patient perception.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Practice Manager",
        "tips": ["Keep staff room and kitchen areas clean.",
                 "Report pest sightings with the room and time.",
                 "Reduce clutter in storage and lab areas.",
                 "Keep external doors closed and monitor damaged seals.",
                 "Manage clinical and general waste carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "staff rooms or storage."),
                   ("Heavy ant or", "cockroach activity."),
                   ("Wasp nests", "near entries or car parks."),
                   ("Fly activity", "around waste areas."),
                   ("Any recurring pest issue", "affecting patients or presentation.")],
        "core": ["Routine pest management for dental environments",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Fly management around waste and staff areas",
                 "Termite inspections and treatments",
                 "Compliance-ready reporting and documentation"],
        "why": ["Clinically aware approach", "Minimal disruption to appointments",
                "Compliance-ready reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Dental Practice",
        "sr_service_type": "Routine dental practice pest service",
        "sr_contact": "Practice Manager",
        "sr_areas": ["reception and waiting", "surgeries", "sterilisation room",
                     "staff room", "bin area"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in storage area",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near rear waste area"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided practice recommendations"],
        "sr_recs": ["improve waste area sanitation", "seal minor entry gaps",
                    "continue monitoring external entry points",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "agedcare": {
        "industry": "Aged Care & Retirement Living",
        "so_word": "AGED CARE",
        "prevention_title": "AGED CARE",
        "focus": "AGED CARE FACILITIES",
        "job_prefix": "AC",
        "sector": "aged care homes, retirement villages and residential care providers",
        "cta_sector": "aged care",
        "audience": "Facility and village managers",
        "site_word": "home",
        "site_label": "Facility name:",
        "risk_clause": "keep residents, staff and visitors safe",
        "discreet": "We work quietly and respectfully around residents and staff.",
        "so_body": "Slug-A-Bug helps aged care homes and retirement villages "
                   "manage pest pressure around residents, keep "
                   "accreditation-ready records and respond quickly when issues "
                   "are reported.",
        "areas11": ["Reception and lounges", "Resident rooms", "Dining rooms",
                    "Commercial kitchens", "Servery areas", "Laundry", "Amenities",
                    "Storage rooms", "Bin and waste areas", "Gardens and courtyards",
                    "Perimeters"],
        "areas9": ["Reception and lounges", "Resident rooms", "Dining rooms",
                   "Kitchens", "Laundry", "Amenities", "Storage rooms",
                   "Bin and waste areas", "Gardens and perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Termite inspection", "Low-odour targeted treatments",
                   "Wasp nest control", "Accreditation support program"],
        "access6": ["Preferred service times", "Resident notification requirements",
                    "Infection control requirements", "Restricted or secure wings",
                    "Recent pest reports or photos", "Previous service history"],
        "challenges": ["Recurring pest concerns near kitchen and waste areas.",
                       "Staff reported occasional ant and cockroach activity.",
                       "Management needed documentation ready for accreditation."],
        "solutions": ["Completed a detailed facility review.",
                      "Identified risk areas and entry points.",
                      "Implemented a routine, low-odour service program with "
                      "targeted treatments and monitoring.",
                      "Provided accreditation-ready reports and recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence from residents, families and staff.",
                    "Documentation ready for accreditation and audits."],
        "why_matters": ["Aged care decision-makers need a pest partner who "
                        "understands resident wellbeing, accreditation and family "
                        "expectations.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Facility Manager",
        "tips": ["Keep kitchen, servery and dining areas clean.",
                 "Report pest sightings with the wing and room number.",
                 "Reduce clutter in storage and laundry areas.",
                 "Keep external doors closed and monitor damaged seals.",
                 "Manage bins and waste areas carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "kitchens or storage."),
                   ("Heavy ant or", "cockroach activity."),
                   ("Wasp nests", "near courtyards or entries."),
                   ("Fly activity", "around waste areas."),
                   ("Any recurring pest issue", "affecting residents or presentation.")],
        "core": ["Routine pest management for aged care environments",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Fly management around kitchens and waste areas",
                 "Termite inspections and treatments",
                 "Discreet, low-odour programs around residents"],
        "why": ["Discreet, low-odour approach", "Minimal disruption to residents",
                "Accreditation-ready reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Aged Care Home",
        "sr_service_type": "Routine aged care facility pest service",
        "sr_contact": "Facility Manager",
        "sr_areas": ["reception and lounge", "commercial kitchen", "dining room",
                     "laundry", "bin area"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in storage area",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near rear waste area"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided management recommendations"],
        "sr_recs": ["improve waste area sanitation", "seal minor entry gaps",
                    "continue monitoring courtyard edges",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "hotels": {
        "industry": "Hotels & Accommodation",
        "so_word": "HOTEL",
        "prevention_title": "HOTEL",
        "focus": "HOTELS AND RESORTS",
        "job_prefix": "HT",
        "sector": "hotels, resorts and accommodation providers",
        "cta_sector": "hotel",
        "audience": "Hotel and accommodation managers",
        "site_word": "property",
        "site_label": "Property name:",
        "risk_clause": "protect guests, reviews and room availability",
        "discreet": "We work discreetly around guests and back of house.",
        "so_body": "Slug-A-Bug helps hotels, resorts and accommodation providers "
                   "manage pest pressure across guest rooms and back of house, "
                   "document room clearances and respond quickly when issues are "
                   "reported.",
        "areas11": ["Lobby and reception", "Guest rooms", "Corridors",
                    "Restaurants and bars", "Commercial kitchens", "Housekeeping stores",
                    "Laundry", "Bin and waste areas", "Plant rooms",
                    "Pool and outdoor areas", "Perimeters"],
        "areas9": ["Lobby and reception", "Guest rooms", "Corridors",
                   "Restaurants and bars", "Kitchens", "Housekeeping stores",
                   "Laundry", "Bin and waste areas", "Perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Termite inspection", "Bed bug inspection and treatment",
                   "Targeted treatments", "Documented room clearance program"],
        "access6": ["Out-of-hours access available", "Preferred service times",
                    "Guest privacy requirements", "Restricted or secure areas",
                    "Recent pest reports or photos", "Previous service history"],
        "challenges": ["Occasional guest reports affecting reviews.",
                       "Back of house and waste areas needed closer attention.",
                       "Management wanted documented clearances before reletting rooms."],
        "solutions": ["Completed a detailed property review.",
                      "Identified risk areas and entry points.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided documented room clearances and clear reports."],
        "results": ["Noticeable reduction in pest activity.",
                    "Faster, documented return of rooms to service.",
                    "Improved confidence from management and staff."],
        "why_matters": ["Accommodation decision-makers need a pest partner who "
                        "protects guest experience, reviews and room revenue.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Hotel Manager",
        "tips": ["Keep kitchen, bar and servery areas clean.",
                 "Report guest sightings with the room number and time.",
                 "Reduce clutter in housekeeping and storage areas.",
                 "Keep back-of-house doors closed and monitor damaged seals.",
                 "Manage bins and waste areas carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "kitchens or storage."),
                   ("Bed bug evidence", "reported in a guest room."),
                   ("Wasp nests", "near balconies or pool areas."),
                   ("Fly activity", "around waste areas."),
                   ("Any recurring pest issue", "affecting guests or reviews.")],
        "core": ["Routine pest management for accommodation environments",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Bed bug inspection, treatment and room clearance",
                 "Termite inspections and treatments",
                 "Discreet servicing across guest and back-of-house areas"],
        "why": ["Discreet around guests", "Documented room clearances",
                "Clear, easy-to-file reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Hotel & Suites",
        "sr_service_type": "Routine accommodation pest service",
        "sr_contact": "Hotel Manager",
        "sr_areas": ["lobby and reception", "guest room sample", "commercial kitchen",
                     "housekeeping store", "bin area"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in housekeeping store",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near rear waste area"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided management recommendations"],
        "sr_recs": ["improve waste area sanitation", "seal minor entry gaps",
                    "continue monitoring back-of-house corridors",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "restaurants": {
        "industry": "Restaurants & Food Premises",
        "so_word": "KITCHEN",
        "prevention_title": "FOOD PREMISES",
        "focus": "RESTAURANTS AND CAFES",
        "job_prefix": "RF",
        "sector": "restaurants, cafes and commercial kitchens",
        "cta_sector": "food premises",
        "audience": "Owners, chefs and venue managers",
        "site_word": "venue",
        "site_label": "Venue name:",
        "risk_clause": "protect food safety, ratings and reputation",
        "discreet": "We service outside trading hours and around prep schedules.",
        "so_body": "Slug-A-Bug helps restaurants, cafes and commercial kitchens "
                   "run documented pest programs, keep inspector-ready records "
                   "and respond quickly when issues are reported.",
        "areas11": ["Dining areas", "Bar and servery", "Commercial kitchens",
                    "Prep areas", "Cool rooms and freezers", "Dry stores",
                    "Dishwash areas", "Amenities", "Bin and waste areas",
                    "Grease trap surrounds", "Perimeters"],
        "areas9": ["Dining areas", "Bar and servery", "Kitchens", "Prep areas",
                   "Cool rooms", "Dry stores", "Dishwash area",
                   "Bin and waste areas", "Perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Cockroach management program", "Fly control program",
                   "Targeted treatments", "Documented food safety program"],
        "access6": ["Out-of-hours or pre-open access", "Preferred service times",
                    "Food safety requirements", "Restricted or secure areas",
                    "Recent pest reports or photos", "Previous service history"],
        "challenges": ["Recurring cockroach evidence around prep and dishwash areas.",
                       "Fly pressure increased around bins in warmer months.",
                       "The venue needed documentation ready for council inspections."],
        "solutions": ["Completed a detailed kitchen and store review.",
                      "Identified risk areas, entry points and harbourage.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided inspector-ready reports and recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence at inspection time.",
                    "Documentation ready for council and auditors."],
        "why_matters": ["Food premises decision-makers need a pest partner who "
                        "understands food safety, council inspections and "
                        "reputation.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Venue Owner",
        "tips": ["Keep prep, dishwash and servery areas clean.",
                 "Report pest sightings with the area and time.",
                 "Reduce clutter in dry stores and under benches.",
                 "Keep back doors closed and monitor damaged seals.",
                 "Manage bins and grease trap areas carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "kitchens or dry stores."),
                   ("Heavy cockroach activity", "in prep or dishwash areas."),
                   ("Wasp nests", "near outdoor dining."),
                   ("Fly activity", "around bins or grease traps."),
                   ("Any recurring pest issue", "affecting food safety or ratings.")],
        "core": ["Documented pest programs for commercial kitchens",
                 "Cockroach management in prep and dishwash areas",
                 "Rodent monitoring and control",
                 "Fly management around bins and grease traps",
                 "Termite inspections and treatments",
                 "Inspector-ready reporting and record-keeping"],
        "why": ["Food-safety aware", "Services outside trading hours",
                "Inspector-ready reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Restaurant & Cafe",
        "sr_service_type": "Routine food premises pest service",
        "sr_contact": "Venue Owner",
        "sr_areas": ["dining area", "commercial kitchen", "dishwash area",
                     "dry store", "bin area"],
        "sr_findings": ["low cockroach activity near dishwash area",
                        "minor spider webbing in dry store",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near rear waste area"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided food safety recommendations"],
        "sr_recs": ["improve bin and grease trap sanitation",
                    "seal minor entry gaps",
                    "continue monitoring prep and dishwash edges",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "taverns": {
        "industry": "Taverns & Pubs",
        "so_word": "VENUE",
        "prevention_title": "LICENSED VENUE",
        "focus": "TAVERNS AND PUBS",
        "job_prefix": "TP",
        "sector": "taverns, pubs, clubs and licensed venues",
        "cta_sector": "venue",
        "audience": "Licensees and venue managers",
        "site_word": "venue",
        "site_label": "Venue name:",
        "risk_clause": "protect food safety, patrons and venue reputation",
        "discreet": "We service outside trading hours and around function bookings.",
        "so_body": "Slug-A-Bug helps taverns, pubs and licensed venues run "
                   "documented pest programs across kitchens, cellars and gaming "
                   "areas, and respond quickly when issues are reported.",
        "areas11": ["Public bar", "Lounge and dining", "Gaming areas",
                    "Commercial kitchens", "Cellars and keg rooms", "Cool rooms",
                    "Dry stores", "Amenities", "Bin and waste areas",
                    "Beer gardens", "Perimeters"],
        "areas9": ["Public bar", "Lounge and dining", "Gaming areas", "Kitchens",
                   "Cellars and keg rooms", "Dry stores", "Amenities",
                   "Bin and waste areas", "Beer garden and perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Cockroach management program", "Fly control program",
                   "Targeted treatments", "Cellar and keg room program"],
        "access6": ["Out-of-hours or pre-open access", "Preferred service times",
                    "Gaming and security requirements", "Restricted or secure areas",
                    "Recent pest reports or photos", "Previous service history"],
        "challenges": ["Recurring cockroach evidence around cellar and bar areas.",
                       "Fly pressure increased around bins and the beer garden.",
                       "The venue needed documentation ready for council inspections."],
        "solutions": ["Completed a detailed venue review.",
                      "Identified risk areas, entry points and harbourage.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided inspector-ready reports and recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence at inspection time.",
                    "Documentation ready for council and auditors."],
        "why_matters": ["Licensed venue decision-makers need a pest partner who "
                        "understands trading hours, food safety and patron "
                        "experience.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Venue Manager",
        "tips": ["Keep bar, kitchen and servery areas clean.",
                 "Report pest sightings with the area and time.",
                 "Reduce clutter in cellars and dry stores.",
                 "Keep back doors closed and monitor damaged seals.",
                 "Manage bins and waste areas carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "cellars or dry stores."),
                   ("Heavy cockroach activity", "in bar or kitchen areas."),
                   ("Wasp nests", "near beer gardens."),
                   ("Fly activity", "around bins or outdoor areas."),
                   ("Any recurring pest issue", "affecting patrons or food safety.")],
        "core": ["Documented pest programs for licensed venues",
                 "Cockroach management in bars, kitchens and cellars",
                 "Rodent monitoring and control",
                 "Fly management around bins and beer gardens",
                 "Termite inspections and treatments",
                 "Inspector-ready reporting and record-keeping"],
        "why": ["Works outside trading hours", "Discreet around patrons",
                "Inspector-ready reports", "Fast response",
                "Experienced, licensed technicians"],
        "sr_property": "Sample Tavern & Bistro",
        "sr_service_type": "Routine licensed venue pest service",
        "sr_contact": "Venue Manager",
        "sr_areas": ["public bar", "commercial kitchen", "cellar", "gaming area",
                     "bin area"],
        "sr_findings": ["low cockroach activity near cellar entry",
                        "minor spider webbing in dry store",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near rear waste area"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided venue recommendations"],
        "sr_recs": ["improve bin area sanitation", "seal minor entry gaps",
                    "continue monitoring cellar and bar edges",
                    "continue regular service program"],
    },
    # ------------------------------------------------------------------ #
    "government": {
        "industry": "Government & Council",
        "so_word": "FACILITY",
        "prevention_title": "PUBLIC FACILITY",
        "focus": "GOVERNMENT FACILITIES",
        "job_prefix": "GC",
        "sector": "government departments, council facilities and public buildings",
        "cta_sector": "facility",
        "audience": "Government and council facilities teams",
        "site_word": "facility",
        "site_label": "Facility name:",
        "risk_clause": "protect public assets, staff and visitors",
        "discreet": "Our technicians are inducted, licensed and work to site rules.",
        "so_body": "Slug-A-Bug helps government departments and councils manage "
                   "pest pressure across public buildings, keep tender-ready "
                   "records and respond quickly when issues are reported.",
        "areas11": ["Reception and public areas", "Offices and meeting rooms",
                    "Libraries and halls", "Depots and workshops", "Staff kitchens",
                    "Amenities", "Storage and plant rooms", "Bin and waste areas",
                    "Parks buildings", "Grounds", "Perimeters"],
        "areas9": ["Reception and public areas", "Offices", "Halls and libraries",
                   "Depots and workshops", "Staff kitchens", "Amenities",
                   "Storage and plant rooms", "Bin and waste areas",
                   "Grounds and perimeter"],
        "scope6": ["Routine pest management", "Rodent monitoring program",
                   "Termite inspection", "Targeted treatments",
                   "Wasp nest control", "Multi-site facility program"],
        "access6": ["Out-of-hours access available", "Preferred service times",
                    "Induction and compliance requirements",
                    "Restricted or secure areas", "Recent pest reports or photos",
                    "Previous service history"],
        "challenges": ["Recurring pest reports across several public buildings.",
                       "Depots and waste areas needed closer attention.",
                       "The team wanted documentation that stands up in a tender."],
        "solutions": ["Completed a detailed multi-site review.",
                      "Identified risk areas and entry points by building.",
                      "Implemented a routine service program with targeted "
                      "treatments and monitoring.",
                      "Provided tender-ready reports and practical recommendations."],
        "results": ["Noticeable reduction in pest activity.",
                    "Improved confidence from facilities staff.",
                    "One consistent, auditable record across sites."],
        "why_matters": ["Government decision-makers need a pest partner who "
                        "documents everything, holds current licences and works to "
                        "site rules.",
                        "They want responsive service, clear paperwork and practical "
                        "results they can rely on."],
        "quote": "Slug-A-Bug made the process simple, responsive and easy to manage.",
        "attribution": "Facilities Coordinator",
        "tips": ["Keep staff kitchens and break areas clean.",
                 "Report pest sightings with the building and room.",
                 "Reduce clutter in storage, depot and plant areas.",
                 "Keep external doors closed and monitor damaged seals.",
                 "Manage bins and waste areas carefully.",
                 "Report leaks and standing water early."],
        "urgent": [("Active termites,", "damaged timber or mudding."),
                   ("Rodent activity near", "depots, kitchens or storage."),
                   ("Heavy ant or", "cockroach activity."),
                   ("Wasp nests", "near entries or public areas."),
                   ("Fly activity", "around waste areas."),
                   ("Any recurring pest issue", "affecting public areas or staff.")],
        "core": ["Routine pest management for public buildings",
                 "Ant, cockroach and spider control",
                 "Rodent monitoring and control",
                 "Fly management around waste and staff areas",
                 "Termite inspections and treatments",
                 "Multi-site programs with tender-ready documentation"],
        "why": ["Tender-ready documentation", "Inducted, licensed technicians",
                "Clear, auditable reports", "Fast response",
                "Experienced in public facilities"],
        "sr_property": "Sample Council Facility",
        "sr_service_type": "Routine public facility pest service",
        "sr_contact": "Facilities Coordinator",
        "sr_areas": ["reception and public area", "offices", "staff kitchen",
                     "depot store", "bin area"],
        "sr_findings": ["low ant activity near external doorway",
                        "minor spider webbing in depot store",
                        "no active termites observed in inspected areas",
                        "housekeeping opportunity identified near rear waste area"],
        "sr_actions": ["replenished monitoring points",
                       "targeted treatment applied to identified activity zones",
                       "removed conducive harbourage where practical",
                       "provided facilities recommendations"],
        "sr_recs": ["improve waste area sanitation", "seal minor entry gaps",
                    "continue monitoring building perimeters",
                    "continue regular service program"],
    },
}

# CSV `Industry` value -> PROFILES key
INDUSTRY_TO_KEY = {p["industry"]: k for k, p in PROFILES.items()}


# ---------------------------------------------------------------------- #
# Three short fields that read better authored than derived. Merged into
# PROFILES on import so every sector still lives in one dict.
#   approach      -> Capability overview: "practical, {approach} pest
#                    management programs"
#   case_subject  -> Case Study subhead: "improved outcomes in a {case_subject}"
#   case_intro    -> Case Study red intro panel
# ---------------------------------------------------------------------- #
_EXTRA = {
    "schools": {
        "approach": "school-safe",
        "case_subject": "busy school campus",
        "case_intro": "A busy primary school was experiencing recurring ant "
                      "activity near the canteen and staff reported occasional "
                      "cockroach sightings around the bin area. Management needed "
                      "responsive service, clear communication and practical results.",
    },
    "childcare": {
        "approach": "child-safe",
        "case_subject": "busy child care centre",
        "case_intro": "A busy child care centre was experiencing recurring ant "
                      "activity near outdoor play edges and staff reported "
                      "occasional cockroach sightings in the kitchen and bin area. "
                      "Management needed responsive service, clear communication "
                      "and practical results.",
    },
    "universities": {
        "approach": "campus-wide",
        "case_subject": "busy university campus",
        "case_intro": "A multi-building campus was receiving pest reports from "
                      "several faculties and food outlets, with the heaviest "
                      "pressure around waste compounds. Facilities needed "
                      "responsive service, one clear reporting trail and practical "
                      "results.",
    },
    "strata": {
        "approach": "common property",
        "case_subject": "busy residential scheme",
        "case_intro": "A residential scheme was receiving repeat pest complaints "
                      "from residents in shared corridors and the basement, with "
                      "the bin room a recurring source. The committee needed "
                      "responsive service, clear scope and practical results.",
    },
    "residential": {
        "approach": "community-wide",
        "case_subject": "busy lifestyle village",
        "case_intro": "A lifestyle village was receiving pest reports from "
                      "residents around the community centre and shared BBQ area, "
                      "with waste points a recurring source. Management needed "
                      "responsive service, clear communication and practical "
                      "results.",
    },
    "retail": {
        "approach": "centre-wide",
        "case_subject": "busy shopping centre",
        "case_intro": "A shopping centre was receiving pest reports from food "
                      "court tenancies, with the loading dock and waste compound "
                      "under the most pressure. Centre management needed "
                      "responsive service, tenant coordination and practical "
                      "results.",
    },
    "industrial": {
        "approach": "site-practical",
        "case_subject": "busy distribution facility",
        "case_intro": "A distribution facility was finding recurring rodent "
                      "evidence around the dock and racking, and staff reported "
                      "occasional cockroach sightings in the break room. "
                      "Management needed responsive service, audit-ready records "
                      "and practical results.",
    },
    "medical": {
        "approach": "clinically-aware",
        "case_subject": "busy medical centre",
        "case_intro": "A busy medical centre was experiencing recurring ant "
                      "activity near the waiting area and staff reported "
                      "occasional cockroach sightings around the waste store. The "
                      "practice needed responsive service, accreditation-ready "
                      "records and practical results.",
    },
    "dental": {
        "approach": "clinically-aware",
        "case_subject": "busy dental practice",
        "case_intro": "A busy dental practice was experiencing recurring ant "
                      "activity near the reception entry and staff reported "
                      "occasional cockroach sightings around the waste store. The "
                      "practice needed responsive service, compliance-ready "
                      "records and practical results.",
    },
    "agedcare": {
        "approach": "discreet, low-odour",
        "case_subject": "busy aged care home",
        "case_intro": "An aged care home was experiencing recurring ant activity "
                      "near the servery and staff reported occasional cockroach "
                      "sightings around the bin area. Management needed discreet "
                      "service, accreditation-ready records and practical results.",
    },
    "hotels": {
        "approach": "discreet",
        "case_subject": "busy hotel property",
        "case_intro": "A busy hotel was receiving occasional guest reports "
                      "affecting reviews, with back-of-house and waste areas under "
                      "the most pressure. Management needed discreet service, "
                      "documented room clearances and practical results.",
    },
    "restaurants": {
        "approach": "food-safety focused",
        "case_subject": "busy commercial kitchen",
        "case_intro": "A busy restaurant was finding recurring cockroach evidence "
                      "around the dishwash area and fly pressure was rising near "
                      "the bins. The venue needed responsive service, "
                      "inspector-ready records and practical results.",
    },
    "taverns": {
        "approach": "venue-practical",
        "case_subject": "busy licensed venue",
        "case_intro": "A busy tavern was finding recurring cockroach evidence "
                      "around the cellar and bar, and fly pressure was rising near "
                      "the beer garden bins. The venue needed responsive service, "
                      "inspector-ready records and practical results.",
    },
    "government": {
        "approach": "tender-ready",
        "case_subject": "busy council facility",
        "case_intro": "A council was receiving pest reports across several public "
                      "buildings, with depots and waste areas under the most "
                      "pressure. The facilities team needed responsive service, "
                      "tender-ready records and practical results.",
    },
}

for _key, _fields in _EXTRA.items():
    PROFILES[_key].update(_fields)
